CREATE TABLE cartas( id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50), URL VARCHAR(150));
INSERT INTO cartas (NAME, URL) VALUES ('O Louco', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Mago', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Sacerdotisa', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Imperatriz', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Imperador', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Hierofante', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('Os Amantes', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Carro', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Justiça', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Eremita', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Roda da Fortuna', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Força', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Enforcado', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Morte', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Temperança', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Diabo', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Torre', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Estrela', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Lua', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Sol', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Julgamento', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Mundo', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Faraó', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Anúbis', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Osíris', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Rá', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Thoth', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Deusa Maat', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Deusa Ísis', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Seth', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Ptah', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Hórus', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Deus Amon', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Esfinge', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Pirâmide', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Obelisco', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Casa da Vida', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Templo', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Árvore da Vida', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Cetro', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Coroa', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Ankh', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Pedra da Vida', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O LIVRO DOS MORTOS', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Olho de Hórus', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Escaravelho', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Bastão de Osíris', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Serpente', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Fênix', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('O Sarcófago', 'https://exemplo.com/louco');
INSERT INTO cartas (NAME, URL) VALUES ('A Múmia', 'https://exemplo.com/louco');